// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/service/apkmgt/organizationds.proto

package org.wso2.apk.enforcer.discovery.service.apkmgt;

public final class OrganizationDsProto {
  private OrganizationDsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * [#protodoc-title: OrganizationDS]
   * </pre>
   *
   * Protobuf service {@code discovery.service.apkmgt.APKMgtOrgDiscoveryService}
   */
  public static abstract class APKMgtOrgDiscoveryService
      implements com.google.protobuf.Service {
    protected APKMgtOrgDiscoveryService() {}

    public interface Interface {
      /**
       * <code>rpc StreamAPKMgtOrganizations(stream .envoy.service.discovery.v3.DiscoveryRequest) returns (stream .envoy.service.discovery.v3.DiscoveryResponse);</code>
       */
      public abstract void streamAPKMgtOrganizations(
          com.google.protobuf.RpcController controller,
          io.envoyproxy.envoy.service.discovery.v3.DiscoveryRequest request,
          com.google.protobuf.RpcCallback<io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new APKMgtOrgDiscoveryService() {
        @java.lang.Override
        public  void streamAPKMgtOrganizations(
            com.google.protobuf.RpcController controller,
            io.envoyproxy.envoy.service.discovery.v3.DiscoveryRequest request,
            com.google.protobuf.RpcCallback<io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse> done) {
          impl.streamAPKMgtOrganizations(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.streamAPKMgtOrganizations(controller, (io.envoyproxy.envoy.service.discovery.v3.DiscoveryRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return io.envoyproxy.envoy.service.discovery.v3.DiscoveryRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc StreamAPKMgtOrganizations(stream .envoy.service.discovery.v3.DiscoveryRequest) returns (stream .envoy.service.discovery.v3.DiscoveryResponse);</code>
     */
    public abstract void streamAPKMgtOrganizations(
        com.google.protobuf.RpcController controller,
        io.envoyproxy.envoy.service.discovery.v3.DiscoveryRequest request,
        com.google.protobuf.RpcCallback<io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.wso2.apk.enforcer.discovery.service.apkmgt.OrganizationDsProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.streamAPKMgtOrganizations(controller, (io.envoyproxy.envoy.service.discovery.v3.DiscoveryRequest)request,
            com.google.protobuf.RpcUtil.<io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return io.envoyproxy.envoy.service.discovery.v3.DiscoveryRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.wso2.apk.enforcer.discovery.service.apkmgt.OrganizationDsProto.APKMgtOrgDiscoveryService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void streamAPKMgtOrganizations(
          com.google.protobuf.RpcController controller,
          io.envoyproxy.envoy.service.discovery.v3.DiscoveryRequest request,
          com.google.protobuf.RpcCallback<io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse.class,
            io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse streamAPKMgtOrganizations(
          com.google.protobuf.RpcController controller,
          io.envoyproxy.envoy.service.discovery.v3.DiscoveryRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse streamAPKMgtOrganizations(
          com.google.protobuf.RpcController controller,
          io.envoyproxy.envoy.service.discovery.v3.DiscoveryRequest request)
          throws com.google.protobuf.ServiceException {
        return (io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          io.envoyproxy.envoy.service.discovery.v3.DiscoveryResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:discovery.service.apkmgt.APKMgtOrgDiscoveryService)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2wso2/discovery/service/apkmgt/organiza" +
      "tionds.proto\022\030discovery.service.apkmgt\032*" +
      "envoy/service/discovery/v3/discovery.pro" +
      "to2\233\001\n\031APKMgtOrgDiscoveryService\022~\n\031Stre" +
      "amAPKMgtOrganizations\022,.envoy.service.di" +
      "scovery.v3.DiscoveryRequest\032-.envoy.serv" +
      "ice.discovery.v3.DiscoveryResponse\"\000(\0010\001" +
      "B\220\001\n.org.wso2.apk.enforcer.discovery.ser" +
      "vice.apkmgtB\023OrganizationDsProtoP\000ZDgith" +
      "ub.com/envoyproxy/go-control-plane/wso2/" +
      "discovery/service/apkmgt\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.envoyproxy.envoy.service.discovery.v3.DiscoveryProto.getDescriptor(),
        });
    io.envoyproxy.envoy.service.discovery.v3.DiscoveryProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
