// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/apkmgt/organization.proto

package org.wso2.apk.enforcer.discovery.apkmgt;

public final class ApkMgtOrganizationProto {
  private ApkMgtOrganizationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrganizationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wso2.discovery.apkmgt.Organization)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
     */
    java.util.List<org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment> 
        getEnvironmentsList();
    /**
     * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
     */
    org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment getEnvironments(int index);
    /**
     * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
     */
    int getEnvironmentsCount();
    /**
     * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
     */
    java.util.List<? extends org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.EnvironmentOrBuilder> 
        getEnvironmentsOrBuilderList();
    /**
     * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
     */
    org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.EnvironmentOrBuilder getEnvironmentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code wso2.discovery.apkmgt.Organization}
   */
  public static final class Organization extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wso2.discovery.apkmgt.Organization)
      OrganizationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Organization.newBuilder() to construct.
    private Organization(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Organization() {
      id_ = "";
      name_ = "";
      environments_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Organization();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Organization(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                environments_ = new java.util.ArrayList<org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment>();
                mutable_bitField0_ |= 0x00000001;
              }
              environments_.add(
                  input.readMessage(org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          environments_ = java.util.Collections.unmodifiableList(environments_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.internal_static_wso2_discovery_apkmgt_Organization_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.internal_static_wso2_discovery_apkmgt_Organization_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization.class, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENVIRONMENTS_FIELD_NUMBER = 3;
    private java.util.List<org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment> environments_;
    /**
     * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
     */
    @java.lang.Override
    public java.util.List<org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment> getEnvironmentsList() {
      return environments_;
    }
    /**
     * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.EnvironmentOrBuilder> 
        getEnvironmentsOrBuilderList() {
      return environments_;
    }
    /**
     * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
     */
    @java.lang.Override
    public int getEnvironmentsCount() {
      return environments_.size();
    }
    /**
     * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
     */
    @java.lang.Override
    public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment getEnvironments(int index) {
      return environments_.get(index);
    }
    /**
     * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
     */
    @java.lang.Override
    public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.EnvironmentOrBuilder getEnvironmentsOrBuilder(
        int index) {
      return environments_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < environments_.size(); i++) {
        output.writeMessage(3, environments_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (int i = 0; i < environments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, environments_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization)) {
        return super.equals(obj);
      }
      org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization other = (org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getEnvironmentsList()
          .equals(other.getEnvironmentsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getEnvironmentsCount() > 0) {
        hash = (37 * hash) + ENVIRONMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getEnvironmentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wso2.discovery.apkmgt.Organization}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wso2.discovery.apkmgt.Organization)
        org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.OrganizationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.internal_static_wso2_discovery_apkmgt_Organization_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.internal_static_wso2_discovery_apkmgt_Organization_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization.class, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization.Builder.class);
      }

      // Construct using org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEnvironmentsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        if (environmentsBuilder_ == null) {
          environments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          environmentsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.internal_static_wso2_discovery_apkmgt_Organization_descriptor;
      }

      @java.lang.Override
      public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization getDefaultInstanceForType() {
        return org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization.getDefaultInstance();
      }

      @java.lang.Override
      public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization build() {
        org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization buildPartial() {
        org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization result = new org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        if (environmentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            environments_ = java.util.Collections.unmodifiableList(environments_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.environments_ = environments_;
        } else {
          result.environments_ = environmentsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization) {
          return mergeFrom((org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization other) {
        if (other == org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (environmentsBuilder_ == null) {
          if (!other.environments_.isEmpty()) {
            if (environments_.isEmpty()) {
              environments_ = other.environments_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEnvironmentsIsMutable();
              environments_.addAll(other.environments_);
            }
            onChanged();
          }
        } else {
          if (!other.environments_.isEmpty()) {
            if (environmentsBuilder_.isEmpty()) {
              environmentsBuilder_.dispose();
              environmentsBuilder_ = null;
              environments_ = other.environments_;
              bitField0_ = (bitField0_ & ~0x00000001);
              environmentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEnvironmentsFieldBuilder() : null;
            } else {
              environmentsBuilder_.addAllMessages(other.environments_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment> environments_ =
        java.util.Collections.emptyList();
      private void ensureEnvironmentsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          environments_ = new java.util.ArrayList<org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment>(environments_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.Builder, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.EnvironmentOrBuilder> environmentsBuilder_;

      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public java.util.List<org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment> getEnvironmentsList() {
        if (environmentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(environments_);
        } else {
          return environmentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public int getEnvironmentsCount() {
        if (environmentsBuilder_ == null) {
          return environments_.size();
        } else {
          return environmentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment getEnvironments(int index) {
        if (environmentsBuilder_ == null) {
          return environments_.get(index);
        } else {
          return environmentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public Builder setEnvironments(
          int index, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment value) {
        if (environmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEnvironmentsIsMutable();
          environments_.set(index, value);
          onChanged();
        } else {
          environmentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public Builder setEnvironments(
          int index, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.Builder builderForValue) {
        if (environmentsBuilder_ == null) {
          ensureEnvironmentsIsMutable();
          environments_.set(index, builderForValue.build());
          onChanged();
        } else {
          environmentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public Builder addEnvironments(org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment value) {
        if (environmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEnvironmentsIsMutable();
          environments_.add(value);
          onChanged();
        } else {
          environmentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public Builder addEnvironments(
          int index, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment value) {
        if (environmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEnvironmentsIsMutable();
          environments_.add(index, value);
          onChanged();
        } else {
          environmentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public Builder addEnvironments(
          org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.Builder builderForValue) {
        if (environmentsBuilder_ == null) {
          ensureEnvironmentsIsMutable();
          environments_.add(builderForValue.build());
          onChanged();
        } else {
          environmentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public Builder addEnvironments(
          int index, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.Builder builderForValue) {
        if (environmentsBuilder_ == null) {
          ensureEnvironmentsIsMutable();
          environments_.add(index, builderForValue.build());
          onChanged();
        } else {
          environmentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public Builder addAllEnvironments(
          java.lang.Iterable<? extends org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment> values) {
        if (environmentsBuilder_ == null) {
          ensureEnvironmentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, environments_);
          onChanged();
        } else {
          environmentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public Builder clearEnvironments() {
        if (environmentsBuilder_ == null) {
          environments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          environmentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public Builder removeEnvironments(int index) {
        if (environmentsBuilder_ == null) {
          ensureEnvironmentsIsMutable();
          environments_.remove(index);
          onChanged();
        } else {
          environmentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.Builder getEnvironmentsBuilder(
          int index) {
        return getEnvironmentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.EnvironmentOrBuilder getEnvironmentsOrBuilder(
          int index) {
        if (environmentsBuilder_ == null) {
          return environments_.get(index);  } else {
          return environmentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public java.util.List<? extends org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.EnvironmentOrBuilder> 
           getEnvironmentsOrBuilderList() {
        if (environmentsBuilder_ != null) {
          return environmentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(environments_);
        }
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.Builder addEnvironmentsBuilder() {
        return getEnvironmentsFieldBuilder().addBuilder(
            org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.getDefaultInstance());
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.Builder addEnvironmentsBuilder(
          int index) {
        return getEnvironmentsFieldBuilder().addBuilder(
            index, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.getDefaultInstance());
      }
      /**
       * <code>repeated .wso2.discovery.apkmgt.Environment environments = 3;</code>
       */
      public java.util.List<org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.Builder> 
           getEnvironmentsBuilderList() {
        return getEnvironmentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.Builder, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.EnvironmentOrBuilder> 
          getEnvironmentsFieldBuilder() {
        if (environmentsBuilder_ == null) {
          environmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.Builder, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.EnvironmentOrBuilder>(
                  environments_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          environments_ = null;
        }
        return environmentsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wso2.discovery.apkmgt.Organization)
    }

    // @@protoc_insertion_point(class_scope:wso2.discovery.apkmgt.Organization)
    private static final org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization();
    }

    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Organization>
        PARSER = new com.google.protobuf.AbstractParser<Organization>() {
      @java.lang.Override
      public Organization parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Organization(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Organization> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Organization> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Organization getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EnvironmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wso2.discovery.apkmgt.Environment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code wso2.discovery.apkmgt.Environment}
   */
  public static final class Environment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wso2.discovery.apkmgt.Environment)
      EnvironmentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Environment.newBuilder() to construct.
    private Environment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Environment() {
      id_ = "";
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Environment();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Environment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.internal_static_wso2_discovery_apkmgt_Environment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.internal_static_wso2_discovery_apkmgt_Environment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.class, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment)) {
        return super.equals(obj);
      }
      org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment other = (org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wso2.discovery.apkmgt.Environment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wso2.discovery.apkmgt.Environment)
        org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.EnvironmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.internal_static_wso2_discovery_apkmgt_Environment_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.internal_static_wso2_discovery_apkmgt_Environment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.class, org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.Builder.class);
      }

      // Construct using org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.internal_static_wso2_discovery_apkmgt_Environment_descriptor;
      }

      @java.lang.Override
      public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment getDefaultInstanceForType() {
        return org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.getDefaultInstance();
      }

      @java.lang.Override
      public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment build() {
        org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment buildPartial() {
        org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment result = new org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment) {
          return mergeFrom((org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment other) {
        if (other == org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wso2.discovery.apkmgt.Environment)
    }

    // @@protoc_insertion_point(class_scope:wso2.discovery.apkmgt.Environment)
    private static final org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment();
    }

    public static org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Environment>
        PARSER = new com.google.protobuf.AbstractParser<Environment>() {
      @java.lang.Override
      public Environment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Environment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Environment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Environment> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wso2.apk.enforcer.discovery.apkmgt.ApkMgtOrganizationProto.Environment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_apkmgt_Organization_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_apkmgt_Organization_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_apkmgt_Environment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_apkmgt_Environment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(wso2/discovery/apkmgt/organization.pro" +
      "to\022\025wso2.discovery.apkmgt\"b\n\014Organizatio" +
      "n\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\0228\n\014environme" +
      "nts\030\003 \003(\0132\".wso2.discovery.apkmgt.Enviro" +
      "nment\"\'\n\013Environment\022\n\n\002id\030\001 \001(\t\022\014\n\004name" +
      "\030\002 \001(\tB\210\001\n&org.wso2.apk.enforcer.discove" +
      "ry.apkmgtB\027ApkMgtOrganizationProtoP\000ZCgi" +
      "thub.com/envoyproxy/go-control-plane/wso" +
      "2/discovery/apkmgt;apkmgtb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wso2_discovery_apkmgt_Organization_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wso2_discovery_apkmgt_Organization_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_apkmgt_Organization_descriptor,
        new java.lang.String[] { "Id", "Name", "Environments", });
    internal_static_wso2_discovery_apkmgt_Environment_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wso2_discovery_apkmgt_Environment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_apkmgt_Environment_descriptor,
        new java.lang.String[] { "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
