// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/apkmgt/organization_list.proto

package org.wso2.apk.enforcer.discovery.apkmgt;

public interface OrganizationListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wso2.discovery.apkmgt.OrganizationList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .wso2.discovery.apkmgt.Organization list = 2;</code>
   */
  java.util.List<org.wso2.apk.enforcer.discovery.apkmgt.OrganizationProto.Organization> 
      getListList();
  /**
   * <code>repeated .wso2.discovery.apkmgt.Organization list = 2;</code>
   */
  org.wso2.apk.enforcer.discovery.apkmgt.OrganizationProto.Organization getList(int index);
  /**
   * <code>repeated .wso2.discovery.apkmgt.Organization list = 2;</code>
   */
  int getListCount();
  /**
   * <code>repeated .wso2.discovery.apkmgt.Organization list = 2;</code>
   */
  java.util.List<? extends org.wso2.apk.enforcer.discovery.apkmgt.OrganizationProto.OrganizationOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .wso2.discovery.apkmgt.Organization list = 2;</code>
   */
  org.wso2.apk.enforcer.discovery.apkmgt.OrganizationProto.OrganizationOrBuilder getListOrBuilder(
      int index);
}
