// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/apkmgt/organization_list.proto

package org.wso2.apk.enforcer.discovery.apkmgt;

public final class OrganizationListProto {
  private OrganizationListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_apkmgt_OrganizationList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_apkmgt_OrganizationList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-wso2/discovery/apkmgt/organization_lis" +
      "t.proto\022\025wso2.discovery.apkmgt\032(wso2/dis" +
      "covery/apkmgt/organization.proto\"E\n\020Orga" +
      "nizationList\0221\n\004list\030\002 \003(\0132#.wso2.discov" +
      "ery.apkmgt.OrganizationB\206\001\n&org.wso2.apk" +
      ".enforcer.discovery.apkmgtB\025Organization" +
      "ListProtoP\001ZCgithub.com/envoyproxy/go-co" +
      "ntrol-plane/wso2/discovery/apkmgt;apkmgt" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.wso2.apk.enforcer.discovery.apkmgt.OrganizationProto.getDescriptor(),
        });
    internal_static_wso2_discovery_apkmgt_OrganizationList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wso2_discovery_apkmgt_OrganizationList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_apkmgt_OrganizationList_descriptor,
        new java.lang.String[] { "List", });
    org.wso2.apk.enforcer.discovery.apkmgt.OrganizationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
