{{- if or .Values.wso2.apk.dp.enabled .Values.wso2.apk.cp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-common-log-conf
  namespace: {{ .Release.Namespace }}
data:
  config.toml: | 
    [commoncontroller]
    [commoncontroller.server]
      label = "ratelimiter"
    {{ if and .Values.wso2.apk.dp.commonController.configs .Values.wso2.apk.dp.commonController.configs.apiNamespaces }}
    [commoncontroller.operator]
      namespaces = [{{ include "commaJoinedQuotedList" .Values.wso2.apk.dp.commonController.configs.apiNamespaces}}]
    {{ end}}  
    [commoncontroller.keystore]
      certPath = "/home/wso2/security/keystore/commoncontroller.crt"
      keyPath = "/home/wso2/security/keystore/commoncontroller.key"

    [commoncontroller.truststore]
      location = "/home/wso2/security/truststore"

  log_config.toml: |
    # The logging configuration for Adapter

    ## Adapter root Level configurations

    {{- if .Values.wso2.apk.dp.adapter.logging }}
    logLevel = "DEBG" # LogLevels can be "DEBG", "FATL", "ERRO", "WARN", "INFO", "PANC"
    LogFormat = "{{ .Values.wso2.apk.dp.adapter.logging.logFormat | default "TEXT" }}" # Values can be "JSON", "TEXT"
    {{- else }}
    logLevel = "DEBG" # LogLevels can be "DEBG", "FATL", "ERRO", "WARN", "INFO", "PANC"
    LogFormat = "TEXT" # Values can be "JSON", "TEXT"
    {{- end }}

    [rotation]
    MaxSize = 10    # In MegaBytes (MB)
    MaxBackups = 3
    MaxAge =  2   # In days
    Compress = true

    ## Adapter package Level configurations

    [[pkg]]
    name = "github.com/wso2/apk/adapter/internal/adapter"
    logLevel = "INFO" # LogLevels can be "DEBG", "FATL", "ERRO", "WARN", "INFO", "PANC"

    [[pkg]]
    name = "github.com/wso2/apk/adapter/internal/oasparser"
    logLevel = "INFO"
{{- end -}}
