---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cp.wso2.com
  resources:
  - organizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cp.wso2.com
  resources:
  - organizations/finalizers
  verbs:
  - update
- apiGroups:
  - cp.wso2.com
  resources:
  - organizations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dp.wso2.com
  resources:
  - ratelimitpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dp.wso2.com
  resources:
  - ratelimitpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - dp.wso2.com
  resources:
  - ratelimitpolicies/status
  verbs:
  - get
  - patch
  - update
